name: octwave-spotdiff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - opencv
  - scipy
  - ipykernel
  - jupyterlab
  - notebook
  # PyTorch (GPU build)
  - pytorch>=2.2,<3.0
  - torchvision>=0.17
  - torchaudio
  - pytorch-cuda=>12.1
  # Pip packages
  - pip:
      - ultralytics>=8.2.0
      - timm>=0.9.8
      - albumentations>=1.3.1
      - ensemble-boxes>=1.0.9
      - shapely>=2.0.0